language: R
dist: trusty
cache: packages

r:
 - release

sudo: required

apt_packages:
  - libgdal-dev
  - libproj-dev
  - libudunits2-dev
  - libhdf5-serial-dev
  - netcdf-bin
  - libnetcdf-dev

script:
  - R CMD install --configure-args="--with-nc-config=/home/travis/bin/nc-config" ncdf4
