language: R
dist: trusty
cache: packages

r:
 - release

sudo: required

apt_packages:
  - libgdal-dev
  - libproj-dev
  - libudunits2-dev

before install:
  - sudo apt-get install -y libgdal-dev libproj-dev libprotobuf-dev libudunits2-dev netcdf-bin netcdf-devel


script:
  - R CMD install --configure-args="--with-nc-config=/home/travis/bin/nc-config" ncdf4
