---
title: "CubeR Vignette 2 - Process Data"
author: Mattia Rossi
output: html_document
---

Import Libraries
```{r,echo=F}
library("CubeR")
library(tibble)
library(magrittr)
library(raster)
library(tidyr)
library(lubridate)
library(purrr)
library(MonalisR)
library(dplyr)
library(ggplot2)
```


```{r}

coverage<-getCapability()[9]
bands <- coverage_get_bands(coverage = coverage)
coords<-c("620812.02", "5171499.36") %>% as.numeric
NIR <- bands[5]
Red <- bands[4]

nd1.tab <- norm_diff_pixel(coverage, coords, band1=NIR, band2=Red, date = NULL,plot = F) %>% as.tibble
nd1.plot <- norm_diff_pixel(coverage, coords, band1=NIR, band2=Red, date = NULL,plot = T)

nd1.tab
plot(nd1.plot)

```

```{r}

coverage<-getCapability()[9]
NIR <- bands[5]
Red <- bands[4]
bands <- coverage_get_bands(coverage = coverage)
coords<-c("620812.02", "5171499.36") %>% as.numeric
slice_E <- as.character(c(coords[1]-5000, coords[1]+5000))
slice_N <- as.character(c(coords[2]-5000, coords[2]+5000))

times <- coverage_get_timestamps(coverage = coverage)
date<-times[8]

nd1.tiff <- norm_diff_raster(coverage, slice_E, slice_N, date=date, band1=NIR, band2=Red)

nd1.tiff
```


```{r}
# Download Sentinel Data
coverage<-getCapability()[9] # S2 10m Reflectance
bands <- coverage_get_bands(coverage = coverage)
coords<-c("620812.02", "5171499.36") %>% as.numeric

nd1.tab <- norm_diff_pixel(coverage, coords, band1= bands[5], band2= bands[4], plot = F) %>% as.tibble

# Download InSitu Data
mnls_down<-downloadMonalisa(foi="vimes1500",
                            datestart = "2016-03-01 00:00",
                            dateend = "2016-12-31 00:00",
                            property = "Normalized Difference Vegetation Index - average",
                            procedure = "SpectralReflectanceSensor_vimes1500") %>% .[[1]] %>% as.tibble

# Format the Datasets
ndvi.MONA<-mnls_down %>%
  tidyr::separate(TimeStamp,c("Date","Time"),sep=" ") %>% 
  dplyr::filter(.,Time=="10:30:00") %>% 
  dplyr::select(-Time) %>% 
  dplyr::mutate(Date=as_date(Date)) %>% 
  tibble::add_column(Sensor="MONALISA NDVI")

ndvi.S2<-nd1.tab %>% 
  dplyr::mutate(Date=as_date(times)) %>% 
  tibble::add_column(Value=nd1.tab$res) %>% 
  tibble::add_column(Sensor="Raw S2 NDVI 10m") %>% 
  dplyr::select(-c(times,res)) %>% 
  dplyr::filter(year(Date)=="2016" & month(Date)>2)

# Bind
allndvi<-rbind(ndvi.MONA,ndvi.S2) %>% arrange(Date)
allndvi

```

```{r}



ggplot(allndvi,aes(x=Date,y=Value,color=Sensor))+
  geom_line()+
  ggtitle("Combination of Ground and Satellite Data")+
  ylab("NDVI")
  

```






