---
title: "Untitled"
output: html_document
---

Import Library
```{r}
library("CubeR")
library(tibble)
library(magrittr)
library(raster)
```


```{r}

coverage<-getCapability()[9]
bands <- coverage_get_bands(coverage = coverage)
coords<-c("620812.02", "5171499.36") %>% as.numeric
NIR <- bands[5]
Red <- bands[4]

nd1.tab <- norm_diff_pixel(coverage, coords, band1=NIR, band2=Red, date = NULL,plot = F) %>% as.tibble
nd1.plot <- norm_diff_pixel(coverage, coords, band1=NIR, band2=Red, date = NULL,plot = T)

nd1.tab
plot(nd1.plot)

```

```{r}

coverage<-getCapability()[9]
NIR <- bands[5]
Red <- bands[4]
bands <- coverage_get_bands(coverage = coverage)
coords<-c("620812.02", "5171499.36") %>% as.numeric
slice_E <- as.character(c(coords[1]-5000, coords[1]+5000))
slice_N <- as.character(c(coords[2]-5000, coords[2]+5000))

times <- coverage_get_timestamps(coverage = coverage)
date<-times[8]

nd1.tiff <- norm_diff_raster(coverage, slice_E, slice_N, date=date, band1=NIR, band2=Red)

nd1.tiff
```

